#!/usr/bin/with-contenv bash

# copy default config files if they don't exist
[[ ! -f /config/nginx/location-confs/proxy.conf ]] && \
    cp /defaults/nginx/location-confs/proxy.conf.sample /config/nginx/location-confs/proxy.conf
[[ ! -f /config/nginx/server-confs/502.conf ]] && \
    cp /defaults/nginx/server-confs/502.conf.sample /config/nginx/server-confs/502.conf
[[ ! -f /config/nginx/server-confs/ssl.conf ]] && \
    cp /defaults/nginx/server-confs/ssl.conf.sample /config/nginx/server-confs/ssl.conf
[[ ! -f /config/www/502.html ]] && \
    cp /defaults/www/502.html /config/www/502.html

# patch authelia-server.conf for CVE-2021-32637
if [[ -f /config/nginx/server-confs/authelia-server.conf ]]; then
    if ! grep -q 'if ($request_uri ~' /config/nginx/server-confs/authelia-server.conf; then
        sed -i '/internal;/a \ \ \ \ if ($request_uri ~ [^a-zA-Z0-9_+-=\\!@$%&*?~.:#'\''\\;\\(\\)\\[\\]]) { return 401; }' /config/nginx/server-confs/authelia-server.conf
    fi
fi
